site_name: Stinger Tug Guide
theme:
  name: material
  palette:
    scheme: default
      primary: "#B39051"  # Deep Navy Header
      accent: "#051E39"   # Crimson Accent / Links
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
